INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES (STR_TO_DATE('20/04/2021', '%d/%m/%Y'), NULL, 'Comprar tangerinas na venda', 'Mercado Piriti', 'Não comprar apenas as extremamente maduras', 1);

INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES(STR_TO_DATE('13/08/2022', '%d/%m/%Y'),STR_TO_DATE('13/08/2022', '%d/%m/%Y'),'Levar cachorro para passear','Praça das crianças',NULL, 1);

INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES(STR_TO_DATE('15/04/2022', '%d/%m/%Y'), STR_TO_DATE('20/04/2022', '%d/%m/%Y'),'Ir academia', 'Academia','Treinar mais cardio', 1);

INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES(STR_TO_DATE('20/04/2021', '%d/%m/%Y'), STR_TO_DATE('20/04/2021', '%d/%m/%Y'),'Ler ao menos 20 pags', NULL, 'Cronicas da terra Média', 1);

INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES(STR_TO_DATE('13/05/2023', '%d/%m/%Y'), STR_TO_DATE('13/06/2023', '%d/%m/%Y'),'Verificar envio correspondência', 'Correios - rua Parati, 123', 'Reclamar sobre o estravio', 1);

INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES(STR_TO_DATE('20/04/2021', '%d/%m/%Y'),STR_TO_DATE('13/05/2023', '%d/%m/%Y'), 'Agendar reunião', NULL, 'MS Teams <link>', 1);

INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES(STR_TO_DATE('20/04/2021', '%d/%m/%Y'),STR_TO_DATE('13/05/2022', '%d/%m/%Y'), 'Excluir tarefa 1', NULL,NULL, 0);

INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES(STR_TO_DATE('20/04/2021', '%d/%m/%Y'),STR_TO_DATE('06/05/2022', '%d/%m/%Y'), 'Finalizar Tarefa', 'Rua Elis Regina', NULL, 0);

INSERT INTO TAREFAS (DATA_REGISTRO, DATA_CONCLUSAO, DESCRICAO, LOCAL, OBSERVACAO, FLAG_CONCLUIDO)
VALUES(STR_TO_DATE('20/04/2021', '%d/%m/%Y'),STR_TO_DATE('13/05/2023', '%d/%m/%Y'), 'Comprar bolo para comemorar', 'Casa do bolo', 'Pegar o bolo de cenoura com chocolate', 0);
